# Generated by Django 3.1.1 on 2020-09-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20200909_2243'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Category',
        ),
    ]
