# Generated by Django 3.1.1 on 2020-09-12 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(blank=True, default=5, on_delete=django.db.models.deletion.CASCADE, related_name='created_mission', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
