# Generated by Django 3.1.1 on 2020-09-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200910_0750'),
        ('mission', '0002_auto_20200909_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='category',
            field=models.ManyToManyField(related_name='category', to='category.Category'),
        ),
    ]
