# Generated by Django 3.1.1 on 2020-09-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20200912_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='owner',
        ),
    ]
